"""Datasheet generation (Gebru et al., 2021)."""

from __future__ import annotations

from dataclasses import dataclass, field

__all__ = ["DatasheetInfo", "generate_datasheet"]


@dataclass
class DatasheetInfo:
    name: str
    motivation: str = ""
    composition: str = ""
    collection: str = ""
    preprocessing: str = ""
    uses: str = ""
    distribution: str = ""
    maintenance: str = ""
    protected_attributes: list[str] = field(default_factory=list)
    n_rows: int | None = None


def generate_datasheet(info: DatasheetInfo) -> str:
    """Return a Markdown Datasheet for a dataset (Gebru et al. 2021 structure)."""
    size = f"{info.n_rows:,} rows" if info.n_rows else "size not recorded"
    attrs = ", ".join(info.protected_attributes) or "—"
    return f"""# Datasheet — {info.name}

*Generated by EthicLens. Format follows Gebru et al. (2021).*

- **Size:** {size}
- **Protected attributes:** {attrs}

## Motivation
{info.motivation or "Not specified."}

## Composition
{info.composition or "Not specified."}

## Collection process
{info.collection or "Not specified."}

## Preprocessing / cleaning / labeling
{info.preprocessing or "Not specified."}

## Uses
{info.uses or "Fairness auditing and mitigation benchmarking within EthicLens."}

## Distribution
{info.distribution or "Not specified."}

## Maintenance
{info.maintenance or "Not specified."}
"""
