"""Model Card generation (Mitchell et al., 2019), populated from an audit."""

from __future__ import annotations

from fairness_core.types import AuditResult, MetricName

__all__ = ["generate_model_card"]


def generate_model_card(
    result: AuditResult,
    *,
    model_name: str = "Unnamed model",
    dataset: str = "synthetic",
    intended_use: str = "Automated decisioning under fairness review.",
    audit_date: str = "—",
    owner: str = "EquitaTech Systems",
) -> str:
    """Return a Markdown Model Card summarising the model and its fairness audit."""
    flagged = result.flagged_groups
    status = "⚠️ FLAGGED" if flagged else "✅ within thresholds"
    rows = ["| Group | Disparate Impact | 95% CI | Status |", "|---|---|---|---|"]
    for g in result.groups:
        m = g.metric(MetricName.DISPARATE_IMPACT)
        if m is None:
            continue
        ci = f"[{m.ci.low:.2f}, {m.ci.high:.2f}]" if m.ci and m.ci.low == m.ci.low else "—"
        val = f"{m.value:.3f}" if m.value is not None else "—"
        rows.append(f"| {g.group_label} | {val} | {ci} | {'FLAG' if g.flagged else 'OK'} |")
    metric_table = "\n".join(rows)

    return f"""# Model Card — {model_name}

*Generated by EthicLens. Format follows Mitchell et al. (2019).*

## Model details
- **Owner:** {owner}
- **Audit date:** {audit_date}
- **Evaluation dataset:** `{dataset}`
- **Fairness status:** {status}
- **Composite Bias Score:** {_fmt(result.composite_score)} ({result.composite_band})

## Intended use
{intended_use}

## Factors
Protected attributes evaluated: {", ".join(sorted({g.attribute for g in result.groups})) or "—"}.
Subgroups are compared against the highest-selection-rate (privileged) group.

## Metrics
Disparate Impact (4/5ths rule), Statistical Parity Difference, and — when ground-truth
labels are available — Equalized Odds, each reported with a bootstrap 95% confidence interval.
A group is flagged only when its DI confidence interval lies entirely below 0.80.

{metric_table}

## Ethical considerations
Disparate impact below 0.80 is evidence of adverse impact under the EEOC Uniform Guidelines.
This card supports, but does not replace, human review and legal assessment.

## Caveats & recommendations
- The composite score is a triage convenience, **not** a legal standard.
- Confidence intervals widen on small subgroups; treat wide intervals as "unknown".
- Re-audit after any retraining or data shift. See `LIMITATIONS.md`.
"""


def _fmt(x: float | None) -> str:
    return "—" if x is None else f"{x:.3f}"
